[project]
name = "django-simple-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.0",
    "django>=6.0.2",
    "django-types>=0.23.0",
    "python-decouple>=3.8",
]
